### ISSUE TITLE
AzureAppConfiguration@2 task: does not support TrimKeyPrefix

### ISSUE THREAD

**Issue by majorimi** [Azure/AppConfiguration#259]
I'm trying to use File transform task in Azure Pipelines. And I'm providing variables from Azure App Configurations. By using AzureAppConfiguration@2 task to fetch config values dynamically.
According to Azure App Configurations it is recommended/possible to use application, region, etc discriminator key prefixes like:

- WebSite:Configs:data1
- RegionEU:Configs:data1

And in .NET Core these can be removed by using .TrimKeyPrefix(<KeyPrefix>); However in AzureDevops AzureAppConfiguration@2 Task does not have this feature. So this task loads all Keys with full name and when I try to use variables in a File transform task that will fail. Since variables does not match to JSON path.
 
Is it possible to add a new property which would remove the give prefix form all loaded key? Like this trimKeyPrefix: "WebSite:"
```
- task: AzureAppConfiguration@2
      displayName: 'Get Azure App Configurations'
      inputs:
        azureSubscription: ''
        ConfigstoreName: ''
        KeyFilter: 'WebSite:*'
        Label: 'Development'
        * trimKeyPrefix: "WebSite:"
```
I have requested this in the "azure-pipelines-tasks" repo. Not sure why is this Task in a different repo?
https://github.com/microsoft/azure-pipelines-tasks/issues/12236#issue-556258774
