### ISSUE TITLE
Values Being Overwritten When Using Two AzDO Tasks with JSON files Containing Unique Values 

### ISSUE THREAD

**Issue by MattMencel** [Azure/AppConfiguration#398]
I'm trying out the Azure App Configuration Push task in AzDO. Running into an issue... I have a CI label and I need to push both regular k/v properties, as well as Keyvault reference properties with the special content-type.

I run them in two tasks like so...

``` yaml
        steps:
          - task: AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@1
            displayName: "AppConfig Push CI: nonprod-appconfig"
            inputs:
              azureSubscription: "nonprod-svccon"
              ConfigstoreName: "nonprod-appconfig"
              ConfigurationFile: CI.json
              Separator: ","
              Label: CI
          - task: AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@1
            displayName: "AppConfig Push CI-keyvault: nonprod-appconfig"
            inputs:
              azureSubscription: "nonprod-svccon"
              ConfigstoreName: "nonprod-appconfig"
              ConfigurationFile: CI-keyvault.json
              Separator: ","
              Label: CI
              ContentType: "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8"
```

The values in each file are unique.

I originally had Strict: true set, which deletes existing values before applying new ones. I realized however that the second task was overwriting the values of the first with that setting enabled.

I thought setting Strict: false or removing it altogether would be the fix, but when the pipeline runs, both tasks complete but the second task is still removing the values from the first.
