### ISSUE TITLE
Appconfig doesn't work with Kubernetes ConfigMap

### ISSUE THREAD

**Issue by bilak** [Azure/AppConfiguration#409]
Hi,
I'm using [spring-cloud-azure-appconfiguration-config-web](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/azure-spring-cloud-appconfiguration-config-web) with [spring-cloud-kubernetes-config](https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-config).

I want to have some of properties populated from configmap and some dynamically retrieved from appconfig.
So I defined the configmap like this:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}
data:
  application-kubernetes.yaml: |-
    ...
  bootstrap-kubernetes.yaml: |-
    spring:
      cloud:
        azure:
          appconfiguration:
            stores:
              - connection-string: ${APP_CONFIGURATION_CONNECTION_STRING}
```

By this I wanted to configure also the connecitonstring for appconfig. However it looks like the bootstrap is not finished and the appconfig doesn't see the `connection-string` property.

```
Caused by: java.lang.IllegalArgumentException: At least one config store has to be configured.
    at org.springframework.util.Assert.notEmpty(Assert.java:467)
    at com.microsoft.azure.spring.cloud.config.AppConfigurationProperties.validateAndInit(AppConfigurationProperties.java:123)
```

Is scenario where it's used configmap + appconfig supported?

**Comment by zhenlan** [comment]
Hi @bilak,

The `spring-cloud-azure-appconfiguration-config-web` library picks up the value of `spring.cloud.azure.appconfiguration.stores[0].connection-string` from the `bootstrap.properties` or `bootstrap.yaml` file of your spring app (you can find more details in this [quickstart](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app)). This is independent where your app is hosted.

In your case, your app is hosted in Kubernetes. The app has no idea to read configuration from the Kubernets configmap. This is no different from reading any settings for your app. You need to wire up configuration defined in configmap with your app. After you define the connection-string in the configmap (formatting doesn't matter), you pass it to the container where your app will be running as environment variables. Then you can update your `bootstrap.*` file to pick the value from the environment variable.

Hope this helps.

**Comment by bilak** [comment]
Hi @zhenlan 
It's little bit more complicated. It looks like `AppConfigurationProperties#validateAndInit` is evaluated before configmap is read. So even when configmap contains `connection-string` for one store it's not being evaluated.

I've prepared sample application which you can test in minikube and see where the problem is. Maybe we can find some solution how to properly configure that, but I spent day with that and was not able to do so.

[here](https://github.com/bilak-poc/azure-appconfig-kubernetes) is the app. Here is some dummy [connection-string](https://github.com/bilak-poc/azure-appconfig-kubernetes/blob/master/k8s/configmap.yaml#L23) but I believe it's not required untill we resolve the load of properties from configmap.

**Comment by zhenlan** [comment]
I don't see your `bootstrap.yaml` is configured to pick up the value of the connection-string.
https://github.com/bilak-poc/azure-appconfig-kubernetes/blob/master/src/main/resources/bootstrap.yaml

**Comment by bilak** [comment]
It should be take from [here](https://github.com/bilak-poc/azure-appconfig-kubernetes/blob/master/k8s/configmap.yaml#L23) (it's just dummy one)

**Comment by ZhijunZhao** [comment]
@bilak Your mentioned scenario is supported. Below is what I tried out today. 

1. Go through this [Quickstart](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app) and make sure it works perfectly on my local machine. 
2. Package the generated `jar` file to a docker image, say `helloworld`.
```
FROM openjdk
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
```
3. Make sure it still works if running the image locally. Pay attention that I pass the environment variable `APP_CONFIGURATION_CONNECTION_STRING` specifically to the container. `APP_CONFIGURATION_CONNECTION_STRING` has to be set with the app config connection string before running below command.  
```
docker run -p 8080:8080 -e APP_CONFIGURATION_CONNECTION_STRING -it helloworld
```
4. Next is to try running the image inside AKS. 

-    Set up config map. 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  connection-string: "the-connection-string"
```

- Then reference the config map and set it as environment variable for the container.

```
      env:
        - name: APP_CONFIGURATION_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: connection-string
```
