### ISSUE TITLE
Azure App Configuration Push Devops Extensions Doesn't Modify Feature Flags

### ISSUE THREAD

**Issue by furlongmt** [Azure/AppConfiguration#541]
Hi, we enabled CI/CD for our AAC configuration using the Azure CLI because the AAC Devops extension did not work when we tried to update feature flags from our pipeline. This feels like it's a bug, but perhaps this a feature or we had something configured. Our issue with the Azure CLI is that it doesn't include an overwrite option so we can't successfully delete keys/features from our configuration via the pipeline. What do you recommend for a team that wants to keep a single configuration file as the "source of truth" for their AAC? Essentially, we want the "strict" option of the devops extension and we want to include feature flag updates in our pipelines.

**Comment by MaryanneNjeri** [comment]
Hi @furlongmt, thank you for reaching out. We are currently working on supporting importing feature flags from json/yaml file, we'll reach out once we have a release out.

**Comment by avanigupta** [comment]
> Our issue with the Azure CLI is that it doesn't include an overwrite option so we can't successfully delete keys/features from our configuration via the pipeline. 

@furlongmt, can you elaborate on the error you get when using Azure CLI to delete/overwrite key-values and feature flags?
Were you able to try the following CLI commands?
- Overwrite key-value: [az appconfig kv set](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az_appconfig_kv_set)
- Delete key-value: [az appconfig kv delete](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az_appconfig_kv_delete) 
- Overwrite feature flags: [az appconfig feature set](https://docs.microsoft.com/en-us/cli/azure/appconfig/feature?view=azure-cli-latest#az_appconfig_feature_set)
- Delete feature flags: [az appconfig feature delete](https://docs.microsoft.com/en-us/cli/azure/appconfig/feature?view=azure-cli-latest#az_appconfig_feature_delete)

**Comment by furlongmt** [comment]
That's great to hear @MaryanneNjeri! We're very much looking forward to that feature. 

@avanigupta, we aren't seeing any error when using the Azure CLI. We can delete or update key-values, but we are lacking the ability to do something like this (from microsoft docs):
![image](https://user-images.githubusercontent.com/11665769/129029946-04137f93-353b-4be1-8418-6d8e5f4682c8.png)

The key bit is "Enabling strict mode will mean key-value pairs that aren't in the configuration file are deleted from the App Configuration instance". This feature does not seem to be supported by the Azure CLI.

**Comment by avanigupta** [comment]
@furlongmt, thanks for the clarification. You're right, Azure CLI does not support strict mode but you can still achieve the same result in 2 steps in your CI/CD pipeline:
 
**Step 1:** Delete all key-values/feature flags from your AppConfig store by running `az appconfig kv delete --key *`
**Step 2:** Import from your config file using `az appconfig kv import`

In the doc that you shared above, there is more guidance on organizing your key-values with prefix/labels if you plan on using strict mode: [Use strict sync](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-github-action#use-strict-sync).

**Comment by furlongmt** [comment]
Thanks for the suggestion @avanigupta. It's too risky for us to delete all of the keys before importing via the config file (e.g., what if the requests are throttled after deleting?). It sounds like we'll have to wait for the new feature to add importing feature flags from json/yaml to the Azure App Configuration Push task.

**Comment by furlongmt** [comment]
For anyone facing a similar issue, we have separated our configuration file into a key-value file and a feature flag file. We then push the configuration file using the AAC task, and the feature flag file using the az CLI like so:
```
- task: AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@1
    displayName: 'Upload Azure App Configuration'
    inputs:
      ConfigurationFile: configuration.json
      Separator: .
      Strict: true
  - task: AzureCLI@2
    displayName: 'Upload Azure App Features'
    inputs:
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: 'az appconfig kv import -y --name {name} --auth-mode login --source file --path "features.json" --format json --preserve-labels'
```
