### ISSUE TITLE
Azure DevOps Extension 3.6.16 Failing

### ISSUE THREAD

**Issue by Nico-VanHaaster** [Azure/AppConfiguration#556]
As of today our Pipelines have been failing using the version 3.6.16 which appears to be released today.

Using a starter pipeline with App configuration is showing the following output.

![image](https://user-images.githubusercontent.com/11223218/135939933-6bd4cf45-e91e-426d-a392-41b56ef89f2e.png)

**Comment by zhenlan** [comment]
@Nico-VanHaaster thanks for reporting the issue. If this is blocking you, you can reference version 3.5.x for now.

@MaryanneNjeri can you take a look?

**Comment by Nico-VanHaaster** [comment]
@zhenlan do you know how to reference the 3.5.x extension in devops?

**Comment by Nico-VanHaaster** [comment]
I can confirm rolling back to 3.5.16 has unblocked us for now.

```
- task: AzureAppConfiguration@3.5.16
  inputs:
    azureSubscription: 'NovaWorks Production (7961c778-01e4-484b-a230-96813f77f731)'
    ConfigstoreName: 'parliament-portal-pipelines'
    KeyFilter: '*'
    Label: 'test'
```
