### ISSUE TITLE
Azure App Configuration Push task ignores KVSet content type

### ISSUE THREAD

**Issue by odrozd** [Azure/AppConfiguration#696]
### Issue:
When using "Azure App Configuration Push" task with content profile set to "KVSet", content type specified for key values ignored. Instead, all key values are imported with blank content type making it impossible to use this task for pushing key vault references or feature flags using "KVSet" file format

### KVSet file content(taken from [here](https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file)):
```
{
  "items": [
    {
      "key": ".appconfig.featureflag/Beta",
      "value": "{\"id\":\"Beta\",\"description\":\"Beta feature\",\"enabled\":true,\"conditions\":{\"client_filters\":[]}}",
      "label": "dev",
      "content_type": "application/vnd.microsoft.appconfig.ff+json;charset=utf-8",
      "tags": {}
    },
    {
      "key": "Database:ConnectionString",
      "value": "{\"uri\":\"https://foobar.vault.azure.net/secrets/db-secret\"}",
      "label": "test",
      "content_type": "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8",
      "tags": {}
    },
    {
      "key": "Logging:LogLevel:Default",
      "value": "Debug",
      "label": "dev",
      "content_type": null,
      "tags": {}
    }
  ]
}
```

### Azure DevOps Task Output:
![image](https://user-images.githubusercontent.com/16099116/204354106-bee2705f-529c-400c-ad65-136bcec6fe19.png)

### Task YML:
```
- task: AzureAppConfigurationPush@3
  inputs:
    azureSubscription: 'FooSubscription'
    AppConfigurationEndpoint: 'https://bar.azconfig.io'
    ConfigurationFile: 'appConfig.json'
    FileContentProfile: 'appconfig/kvset'
    Strict: true
```

### Azure Portal Result:
![image](https://user-images.githubusercontent.com/16099116/204355473-f5c901a8-3320-498c-a909-2adcd6a464a2.png)

### Additional Notes:
Doing same operation using Azure CLI works as expected:

![image](https://user-images.githubusercontent.com/16099116/204356980-57a93621-ab53-44af-b16e-d75092766d94.png)
