### ISSUE TITLE
How to use "App Configuration" task in an Azure DevOps pipeline in special cases ?

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#701]
Hello,

In an Azure DevOps Pipeline, to get key-values from an App Configuration to use them in a yaml template, I use this yaml task :
```
    - task: AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration@5
      inputs:
        azureSubscription: 'ServiceConnectionName'
        AppConfigurationEndpoint: 'https://ressourcename.azconfig.io'
```

Questions
1) Why a task name so long !
2) Where is the documentation of this yaml tasks v5 ?
3) How to use a private endpoint or a connectionString with this AppConfiguration task ? How to configure it ?
4) Which access rights need the Azure AD account used in the ServiceConnection (for the "azureSubscription" parameter) ?
5) If secrets are in a Key Vault in another azure subscription,  which access rights need the Azure AD account ?

Thanks for your help ?
