### ISSUE TITLE
How to show key-values retreived in Azure DevOps pipeline yaml ?

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#702]
Hello,

In an Azure DevOps Pipeline, to get key-values from an App Configuration to use them in a yaml template, I use this yaml task :
```
    - task: AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration@5
      inputs:
        azureSubscription: 'ServiceConnectionName'
        AppConfigurationEndpoint: 'https://ressource.azconfig.io'
```
After execution, I see this message :
`'4' key-values were retrieved from Azure App Configuration.`

So key-values are well retreived.

But when I try to show the values retreived with this PowerShell task :
```
    - task: PowerShell@2 
      displayName: 'Show AppConfiguration values'
      inputs:
        targetType: 'inline'
        script: |
          echo "cicd-azure = ${env:cicd-azure}"
          echo "TestHello = ${env:Application:Poc:TestHello}"
          echo "Test = $env:Test"
```

I see nothing :
```
cicd-azure = 
TestHello = 
Test = 
```

Why ?
