### ISSUE TITLE
[Question] Configuring Spring Boot App Config Provider to fetch all namespaces

### ISSUE THREAD

**Issue by DhavalShewale** [Azure/AppConfiguration#704]
How can Spring Boot App Config Provider (`azure-spring-cloud-appconfiguration-config`) be configured to fetch all namespaces.

Currently it expects a `keyFilter` in `selects` and it the same is not provided it defaults to `/application`.

We want to configure it in such a way that all namespaces are pulled (without explicitly specifying them) and injected in spring environment.

**Comment by mrm9084** [comment]
Hi, it looks like the way to do this wasn't documented.

If you are using properties, you can do:

```properties
spring.cloud.azure.appconfiguration.stores[0].selects[0].key-filter=
```
where key-filter is listed without any value.

If you are using yaml:

```yaml
spring:
  cloud:
    azure:
      appconfiguration:
        stores:
            selects:
              - 
                key-filter: ''
```
the key filter should be either two single quotes, or two double quotes.
