### ISSUE TITLE
How to retrieve Secret key-values in yaml if we don't know their key names in advance ?

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#705]
Hello,

In an Azure DevOps Pipeline, to get key-values from an App Configuration to use them in a yaml template, I use this yaml task :
```
    - task: AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration@5
      inputs:
        azureSubscription: 'ServiceConnectionName'
        AppConfigurationEndpoint: 'https://ressourcename.azconfig.io'
        KeyFilter: '${{ parameters.appConfigurationKeyFilter }}*'
```

References to Azure Key Vault in App Configuration will be resolved and set as secret variables. In Azure pipelines, secret variables are hidden in the log. They are not passed to tasks as environment variables and instead must be passed as entries.
So, how to pass secret as entries in a YAML task when we don't know the key name of secret in advance ? Each application has different secret names.

For example, I use this PowerShell task to use key-values retrieved from an App Configuration :
```
    - task: PowerShell@2 
      env:
        APPICATIONNAME-CONNECTEDAPP-SECRET: $(ApplicationName-ConnectedApp-Secret)
        APPICATIONNAME-ENVIRONMENT-SECRET: $(ApplicationName-Environment-Secret)
       APPICATIONNAME-VARIABLENAME: $(ApplicationName-VariableName)
      inputs:
        targetType: 'inline'
        script: |

            # Get all key-values without secret
            $keyValues = Get-ChildItem env: | where name -like '${{ parameters.appConfigurationKeyFilter }}*'

           $Secret1 = "$(ApplicationName-ConnectedApp-Secret)"
           $Secret2 = "$(ApplicationName-Environment-Secret)"
           $Secret3 = "$(ApplicationName-VariableName)"
```

Name of Env variables must to be known in advance to be hard coded. How to do when we don't know key names in advance ?
