### ISSUE TITLE
How to use "Trim Key Prefix:" parameter when we pull settings from App Configuration

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#706]
Hello,

In an Azure DevOps Pipeline, to get key-values from an App Configuration to use them in a yaml template, I use this yaml task :
```
    - task: AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration@5
      inputs:
        azureSubscription: 'ServiceConnectionName'
        AppConfigurationEndpoint: 'https://ressourcename.azconfig.io'
        KeyFilter: '${{ parameters.appConfigurationKeyFilter }}*'
```
But how to use the "TrimKeyPrefix:" parameter in the AppConfiguration task ?
If I use it, how to retrieve key-values in all environment variables ?

Now, I use this PowerShell task to use key-values retrieved from an App Configuration :
```
    - task: PowerShell@2 
      inputs:
        targetType: 'inline'
        script: |

            # Get all key-values
            $keyValues = Get-ChildItem env: | where name -like '${{ parameters.appConfigurationKeyFilter }}*'
```

How to do otherwise ?

**Comment by MaryanneNjeri** [comment]
To use "TrimKeyPrefix", specify one or more prefixes that should be trimmed from App Configuration keys before setting them as variables.
Example is:
Key in App Configuration resource 
![image](https://user-images.githubusercontent.com/33903727/211327222-c46515c5-c7c3-4619-ab9c-d517b8f6bc85.png)

```
- task: AzureAppConfiguration@5
  inputs:
    azureSubscription: 'ServiceConnectionName'
    AppConfigurationEndpoint: 'https://resource.azconfig.io'
    key: '*'
    TrimKeyPrefix: 'app:'
```

```
- task: PowerShell@2 
  displayName: 'Show AppConfiguration values'
  inputs:
    targetType: 'inline'
    script: |
      echo "Test 1 = $(test1)"
      echo "Test 2 = $(test2)"
      echo "Test 3 = $env:test3"
```
After specifying the TrimKeyPrefix as "app:",  "app:" is trimmed from the key, and the available variables are _test1_, _test2_, and _test3_.
Please let me know if this helps.
