### ISSUE TITLE
[CLI] az appconfig kv import changes the casing of boolean values

### ISSUE THREAD

**Issue by AlexTorianyk** [Azure/AppConfiguration#725]
I'm running the following from my command line: `az appconfig kv import -n app-config-test -s file --path values.json --format json --separator ':' `

The `values.json` file is a nested json file which looks like this:
```
{
  "Frontend": {
        "hasAccount": true,
        "hasCheckout": true,
        "hasHealthWarning": false,
   },
}
``` 
As a result, I get a bunch of updates in the console, only changing the casing of the first letter for those boolean values ->
```
- {"key": "Frontend:hasAccount", "value": "true"}
+ {"key": "Frontend:hasAccount", "value": "True"}
- {"key": "Frontend:hasHealthWarning", "value": "true"}
+ {"key": "Frontend:hasHealthWarning", "value": "True"}
- {"key": "Frontend:hasCheckout", "value": "false"}
+ {"key": "Frontend:hasCheckout", "value": "False"}
```
Interestingly enough, using the _AzureAppConfigurationPush@3_ task in AzureDevOps results in the expected behaviour -> no changes. This is the code for the task
```
    - task: AzureAppConfigurationPush@3
      displayName: 'Push values to App Configuration'
      inputs:
        azureSubscription: <subscription>
        AppConfigurationEndpoint: <endpoint?
        ConfigurationFile: values.json
        Separator: ':'
        Strict: false
        ImportMode: 'Ignore-Match'
```

I'm looking for a way to unify the behaviour in cli and the azure devops task, perhaps I'm missing some sort of a parameter?
