### ISSUE TITLE
Pushing an empty array/object to app configuration results in "[]" or "{}"

### ISSUE THREAD

**Issue by AlexTorianyk** [Azure/AppConfiguration#731]
To reproduce, just try to import a configuration file with an empty array and/or object:
![image](https://user-images.githubusercontent.com/37710247/226845746-ac0161cf-ad91-499f-b60e-f2b8366c3828.png)

This is quite unexpected for developers, it's quite tedious to explain why they have to delete the whole property if they want to leave an empty array. Some languages(like JavaSrcipt) without strict typing will allow you to loop over the "[]" string as if it was an array 😕

If this is the intended behaviour, could someone lay out the reasoning for it?

**Comment by zhenlan** [comment]
@AlexTorianyk, to help us understand the issue, could you please share the following?
- The content of the file you are importing
- The full CLI command you used for the importing
- Your expected results of the importing

**Comment by AlexTorianyk** [comment]
@zhenlan, sure, I'll provide a more fleshed out example :)
1. Here are the contents of the `example.json` file:
```
{
  "EmptyArray": [],
  "EmptyObject": {},
  "Null": null,
  "String": "Hello World"
}
```

2. The CLI command I'm using for the importing is `az appconfig kv import -n <app-config> -s file --path example.json --format json`, with the following output:
![image](https://user-images.githubusercontent.com/37710247/227133232-1c670a8b-9e74-45ad-918a-8149d2d893cb.png)

3. While I'm not so sure about the _null_, I'd expect both the `EmptyArray` and the `EmptyObject` to not push anything into app configuration. While I can't really come up with a perfect way to represent an empty array in a key-value format, I feel like returning a "[]" string would probably be unintuitive for the majority of developers.

**Comment by AlexTorianyk** [comment]
On an interesting side-note, importing with `separator ':'` results in this output:
![image](https://user-images.githubusercontent.com/37710247/227134433-3b29ace1-c495-4a45-8494-0c964782dc7c.png)
The json is already flattened, so perhaps there's some additional logic that checks for empty arrays and objects when importing with a _separator_?

**Comment by AlexTorianyk** [comment]
And one more question if you don't mind. Ultimately we're pushing the changes through the `AzureAppConfigurationPush@3` task in AzureDevOps. Does that task use the cli under the hood, or is it written separately?

**Comment by AlexTorianyk** [comment]
And what about the `AzureAppConfigurationPush@3` task?
This is the step definition:
```
- task: AzureAppConfigurationPush@3
      inputs:
        azureSubscription: appconfig-${{ parameters.connection }}
        AppConfigurationEndpoint: https://app-config-${{ parameters.target }}.azconfig.io
        ConfigurationFile: combined-values-${{ parameters.value }}.json
        Separator: ':'
        Strict: false
        ImportMode: 'Ignore-Match'
        DryRun: true
      displayName: 'Push values to App Configuration'
```
And I've added an empty array to test things out
![image](https://user-images.githubusercontent.com/37710247/227169127-2f66743f-7f11-483f-816f-724324c99a62.png)
As you can see, the **departments** key would be written to the app configuration if not for the DryRun. It would have the "[]" value
![image](https://user-images.githubusercontent.com/37710247/227169771-1d3becd5-90b1-44f3-b1cf-97f3a15cb967.png)
