### ISSUE TITLE
Is the azureappconfiguration.kubernetesprovider already usable with ServicePrincipals?

### ISSUE THREAD

**Issue by Bjego** [Azure/AppConfiguration#744]
Hey guys,
last week I spotted the release of the azureappconfiguration.kubernetesprovider. 

https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-kubernetes-service

Is it already possible to configure this provider to use a service principal to connect to an App Configuration? We are running some kubernetes clusters on prem and would like to integrate Azure AppConfiguration Services via the new provider. For the KeyVault CSI Provider, we are using the service principal connection method and it works like a charm!

I hope we can connect our containers to AppConfiguration soon.

With best regards,
Bjego

**Comment by RichardChen820** [comment]
Hello @Bjego Thank you for reaching out.

This provider supports service principal authentication similar to how KeyVault CSI provider does. 

You can create a secret with the service principal credential in the same namespace of your `AzureAppConfigurationProvider` resource:

```
kubectl create secret generic app-config-creds \
      --from-literal azure_client_id=<AZURE_CLIENT_ID> \
      --from-literal azure_client_secret=<AZURE_CLIENT_SECRET> \
      --from-literal azure_tenant_id=<AZURE_TENANT_ID>
```

Then you just need to refer to this secret in `spec.auth.servicePrinicipalReference` in your `AzureAppConfigurationProvider` yaml like:
```
apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
  namespace: appconfig-sample
spec:
  endpoint: https://<yourappconfig>.azconfig.io
  target:
    configMapName: configmap-name-to-create
  auth:
    servicePrincipalReference: app-config-creds
```

Let me know if you have more questions.

**Comment by Bjego** [comment]
HI @zhenlan ,
thanks for the hints. Finally I am going to install the driver in kubernetes these days. 

Do you have some more insights?
Do have to enable automatically reloading (like in the keyvault csi driver) ?
Is the a documentation about the AzureAppConfigurationProvider yaml config? Can I filter for e.g. labels and stuff like that?

Kind regards!

**Comment by Bjego** [comment]
> And could you please explain how the keyvault - pull through works?

Okay I got that working with the following yaml:
```
apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  endpoint: https://XXXX.azconfig.io
  target:
    configMapName: appconfig-configmap
  auth:
    servicePrincipalReference: app-config-creds
  keyValues:
    keyVaults:
      auth:
        servicePrincipalReference: app-config-creds
      target:
        secretName: appconfig-secret
    selectors:
      - keyFilter: "*"
        labelFilter: mylabel
    trimKeyPrefixes:
      - "someprefix."
```

**Comment by RichardChen820** [comment]
We are working on the auto refresh feature, it would be available soon in the upcoming new version. 

It would polling a sentinel key ( a key that can be specified by user) periodically, that is similar to how key values be refreshed in the [.Net provider.](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core6x)  Once the provider detects the sentinel key is changed, it will update the configmap and secret with the present data from your AppConfigruation store.

**Comment by Bjego** [comment]
> We are working on the auto refresh feature, it would be available soon in the upcoming new version.
> 
> It would poll a sentinel key ( a key that be specified by user) periodically, which is similar to how key values be refreshed in the [.Net provider.](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core6x) Once the provider detects the sentinel key is changed, it will update the configmap and secret with the present data from your AppConfigruation store.

Just looked up the sentinel key docs. Could you considder using a simple cron pulling way as well?
In the keyvault csi provider - I can simply define a polling / sync intervall for all values - without the  need of a manual changed key.
And I think from the implementation perspective it's also even easier to implement.

https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/enable-auto-rotation-secrets/ 

Not sure how you plan to implement the sync. But I could imagine something like the following yaml. And then the users of the provider can choose - do I want to have:

- a simple time based rotation
- a sentinal key based rotation, with maybe a labelfilter

I'm not quite sure about the sential key - as it is a manual process and people may forget to update it

```yaml
apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  refresh:
    intervall: 2m
    sentinalKey: my.sentinal.key
    sentinalLabelFilter: mylabel
  endpoint: https://XXXX.azconfig.io
  target:
    configMapName: appconfig-configmap
  auth:
    servicePrincipalReference: app-config-creds
  keyValues:
    keyVaults:
      auth:
        servicePrincipalReference: app-config-creds
      target:
        secretName: appconfig-secret
    selectors:
      - keyFilter: "*"
        labelFilter: mylabel
    trimKeyPrefixes:
      - "someprefix."
```
