### ISSUE TITLE
DryRun set to true logs '{"key":"0:key"}' and set to false adds '{"key":"0:key"}' to the app configuration

### ISSUE THREAD

**Issue by jakubtrebacz-dev** [Azure/AppConfiguration#757]
Hi there 
When I run this with dryRun flag set to true I get 
> The following settings will be written to App Configuration:
{"key":"0:key"}
{"key":"0:label"}
{"key":"0:value"}
{"key":"0:content_type"}

the actual json object in the file
```json 
[
{
  "key": "some_key",
  "label": "dev",
  "value": "LOCAL",
  "content_type": "text/plain",
  "tags": {}
}
]
```
I would expect this to log keys and values that are going to change, from value x to value y.
I want to be able to see exactly what is about to change, so when someone is approving the update to production env, they know what will change. 
In general app configuration shouldn't contain any sensitive data ever on any system, that's what you got keyvaults for. This process does not manage what's in keyvault, only a keyvault reference links stored here, which again are not sensitive.

Here is the setup I use
```yaml
steps:
  - task: AzureAppConfigurationPush@5
    inputs:
      azureSubscription: 'SPN'
      configStoreName: 'resource-name'
      configurationFile: $(env).json'
      appConfigurationEndpoint: 'https...'
      separator: ':'
      fileContentProfile: 'appconfig/default'
      strict: false
      dryRun: true 
```

The SPN has RBAC set to data owner. Everything else seems to be fine as far as I can see, apart from the console output.

_____________
UPDATE:
Also, I just run this to apply the change, and it literally added
```json 
{"key":"0:key"}
{"key":"0:label"}
{"key":"0:value"}
{"key":"0:content_type"}
```
into the app configuration, so I suppose there is something fundamentally wrong with the setup. 

![image](https://github.com/Azure/AppConfiguration/assets/25771577/85dd4379-c471-4600-8ee5-8b1c662a57d5)
