### ISSUE TITLE
Azure App Configuration Push Task@5: Undocumented breaking change with feature flags

### ISSUE THREAD

**Issue by supereddie** [Azure/AppConfiguration#760]
With version 5 of AzureAppConfigurationPush it is no longer possible to push settings with the feature flag prefix, resulting in the following error: `Key cannot start with the reserved prefix for feature flags.`

The version 4 of the task works without issue:
```yaml
- task: AzureAppConfigurationPush@4
  displayName: 'Feature flags - Development'
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    AppConfigurationEndpoint: '$(appConfigurationEndpoint)'
    ConfigurationFile: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/feature-flags-test.json'
    Separator: '-'
    Prefix: '.appconfig.featureflag/'
    Depth: '1'
    Label: 'Development'
    ContentType: 'application/vnd.microsoft.appconfig.ff+json;charset=utf-8'
    Strict: true
```

Contents of .json file:
```json
{
  "MyFlagName": {
    "id": "MyFlagName",
    "description": "",
    "enabled": true,
    "conditions": {
      "client_filters": []
    }
  }
}
```

I cannot find this breaking change in the release notes of the task, so I don't know if this change was intentional or not.
