### ISSUE TITLE
Azure app configuration version 5 pushes Azure key vault values as strings

### ISSUE THREAD

**Issue by mohibakhan** [Azure/AppConfiguration#761]
This is my task in DevOps pipeline that pushes key vault values to azure app configuration

steps:
```
- task: AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@4
  displayName: 'Azure App Configuration - Keyvault'
  inputs:
    azureSubscription: '{rgName}'
    AppConfigurationEndpoint: 'https://{appConfig}-eastus.azconfig.io'
    ConfigurationFile: '$(System.DefaultWorkingDirectory)/unzip/deploy_parameters\SBX\sbx_ea_keyvault.parameters.json'
    Separator: ','
    ContentType: 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'
```

If I use the same yaml for version 5 I get a string for value 

e.g. value of app configuration with version 4
`{"uri":"https://{keyvault}.vault.azure.net/secrets/SERVICE-BUS-CONNSTRING"}`

e.g. value of app configuration with version 5
`{\"uri\":\"https://{keyvault}.vault.azure.net/secrets/SERVICE-BUS-CONNSTRING\"}`
