### ISSUE TITLE
Unable to access App Configuration with User Managed Identity in Java spring boot

### ISSUE THREAD

**Issue by charu-jain-sapient** [Azure/AppConfiguration#771]
I am facing issues connecting to azure app configuration with User Managed Identity.

**The issue that I am getting is:**

com.microsoft.aad.msal4j.MsalAzureSDKException: java.util.concurrent.ExecutionException: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, Network is unreachable: no further information.

I am using below dependency in my spring boot application:

`implementation ('com.azure.spring:azure-spring-cloud-appconfiguration-config-web:2.11.0') `

 My bootstrap.yml looks like this:

```
spring:
  application:
    name: app-service
    version: 0.0.1
  cloud:
    azure:
      appconfiguration:
        enabled: ${APP_CONFIGURATION_ENABLED} // true
        managed-identity:
          client-id: ${AZURE_CLIENT_ID}  // some valid client_id, created on azure portal
        stores:
          - endpoint: ${AZURE_END_POINT} // some valid endpoint
```

Please note i have created sample configurations on my azure portal and also exported AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_TENANT_ID properties as environment variables containing valid values.

I am using spring boot version 3.1.0 and have been following this doc:

https://learn.microsoft.com/en-us/java/api/overview/azure/spring-cloud-starter-appconfiguration-config-readme?view=azure-java-stable

The same set of configurations works fine in plain Java, by creating beans explicitily like this:

```
public class Main {

    public static void main(String[] args) {

        TokenCredential credential = new DefaultAzureCredentialBuilder().build();

        ConfigurationClient client = new ConfigurationClientBuilder()
                .credential(credential)
                .endpoint("same endpoint as used above")
                .buildClient();

        ConfigurationSetting retrievedSetting = client.getConfigurationSetting("/application/app-service/appconfig.appUrl", "local");

        System.out.println(retrievedSetting.toString()); // works fine
    }
}
```
but these configurations doesn't work well with spring boot 3.x.

Can anyone point what probably i am doing wrong or what could be the issue here.

Thanks in advance.

Also, I have tested by running application on azure also. still getting "Connection to IMDS endpoint cannot be established, Network is unreachable: no further information."
