### ISSUE TITLE
Pushing an empty array to app configuration results in a configuration which cannot be read by the CLI

### ISSUE THREAD

**Issue by samholder** [Azure/AppConfiguration#788]
Hi. 

I have an issue related to #731, and I understand the reasons given there for the behaviour but I'm not sure this helps. We are using the AzureAppConfigurationPush@6 task to push the config and using the CLI to pull it down so we can compare

I have a config file that looks like this:

	{
	  "MyProfile": {
	       "MYTEST": {
		    "Features": []
	        }
	   }
	}
	
if I upload this config it creates this in the config service:

![image](https://github.com/Azure/AppConfiguration/assets/2073290/013a1aec-c915-4173-8ffa-6dc95e5ceee6)

as you can see it creates `[]` as the value.

if I try and get this config with the CLI tool using this command line: 

`az appconfig kv export --name "namehere" --label "dev_stage" --prefix "ContUsFeatures_" --key "ContUsFeatures_*" --separator ":" --destination "file" --path "./temp.json" --format "json" --yes --skip-features --skip-keyvault "True"`

then it works ok.

if I then update the config to this:

	{
	  "MyProfile": {
	       "MYTEST": {
		    "Features": [
                          "MyFeature"
                     ]
	        }
	   }
	}
	
and then push the config again then when I look at the config in the config explorer I get this:

![image](https://github.com/Azure/AppConfiguration/assets/2073290/0610374f-f8f2-4c35-94ab-a8c444dadce2)

As you can see it has not changed anything, its added the array element 0 now (correctly), but left the unindexed version with the `[]`.

If I use the command line to get the config I now get an error:

`Failed to export key-values to file. Fail to export key-values.list indices must be integers or slices, not str`

we are using `text/plain` as our default when pushing config, but I have tried using `application/json` with the same results

This is causing us to be unable to read config that we have changed if we add elements to an array, or remove them from an array (which is how we ran into this).

I would expect the CLI to handle the empty array->populated array->empty array cases.

in our case we are getting the config before we push to validate the changes in config, so this causes all of our pipelines that do this to fail as soon as we go from empty to populated array, or from populated to empty.

**Comment by jimmyca15** [comment]
Do you import with `strict` mode enabled as detailed [here](https://learn.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az-appconfig-kv-import-optional-parameters)? The reason I ask is because arrays can be tricky with leftover values. If you downsize the array locally, and import it, without strict mode the service will still end up with additional items in the array.

Additionally, strict mode may be able to help here since it should remove the brackets.

Finally, I don't see much value in [] being imported in your example above. This behavior must have been around for a while now without my notice, so will think if I'm missing something, but it seems like it should be changed to not import anything for empty arrays. Does that sound right to you? Or do you have some value in having the array brackets imported for empty array.

**Comment by albertofori** [comment]
Since we flatten arrays when content-type is not "application/json", I agree with @jimmyca15 that nothing should be imported for a key-value with empty array.  If there is any value in an imported empty array, specifying the json content-type should enable this. This way, a change in the array will overwrite the single imported kv which initially had an empty array as the value.

**Comment by samholder** [comment]
We're happy without strict mode, we just don't want the default behaviour to create invalid data with 'normal' operations.

**Comment by albertofori** [comment]
@samholder I just realized you mentioned the behavior that imports an empty array as brackets is in the app configuration push task. Could you provide us with more information on the parameters you use when pushing configuration settings to your store?
cc @MaryanneNjeri

**Comment by samholder** [comment]
Our job looks like this:

```
  - task: AzureAppConfigurationPush@6
    displayName: 'Update app configuration `${{ parameters.prefix }}` | `${{ parameters.contentType }}`'
    inputs:
      azureSubscription: '${{ parameters.azureResourceManager }}'
      appConfigurationEndpoint: '${{ parameters.appConfigurationEndpoint }}'
      configStoreName: '${{ parameters.configStoreName }}'
      configurationFile: '${{ parameters.configurationFile }}'
      ${{ if eq(parameters['contentType'], 'keyvault') }}:
          contentType: 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'
      ${{ else }}:
          contentType: '${{ parameters.contentType }}'
      separator: '${{ parameters.separator }}'
      label: '${{ parameters.label }}'
      prefix: '${{ parameters.prefix }}'
      tags: "{\"deployed_by\": \"pipeline\", \"repo\": \"$(Build.Repository.Name)\", \"commitID\": \"$(Build.SourceVersion)\", \"codeVersion\": \"$(tag.latest)\"}"
      strict: false # Any key-values in the store with the specified prefix and label that are not included in the configuration file will be deleted.
```

The context type is `text\plain`
separator is `:`

I don't think anything matters but let me know if you need any of the other values
