### ISSUE TITLE
Workload identity support in Kubernetes provider

### ISSUE THREAD

**Issue by AbhiReen** [Azure/AppConfiguration#795]
Is there a plan to support Workload identity for the kubernetes provider and do you have a timeline for it?

**Comment by zhenlan** [comment]
Yes, we do have a plan to support workload identity in the near future.

**Comment by RichardChen820** [comment]
Support workload identity is on our radar, we plan to support it at the controller pod level.

To support one-to-many serviceAccount-to-identity map, a new setting would be added in API, sample yaml:
```
apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: demo-provider
spec:
  endpoint: https://contoso.azconfig.io
  target:
    configMapName: configmap-demo
  auth: 
    workloadIdentity:
      managedIdentityClientId: <client id of managed identity>
```

I imagine use workload identity in App Configuration Kubernetes Provider should take following steps:
1. Enable cluster workload identity
2. Create a managed identity, and assign the appropriate role to it.
3. Create federated credential.
3. Set the managed identity client ID to `auth.workloadIdentity.ManagedIdentityClientId` in yaml
