### ISSUE TITLE
Azure App Configuration Push Task@6: Prefix not appended to Key value

### ISSUE THREAD

**Issue by j-noel-b** [Azure/AppConfiguration#810]
With version 6 of the AzureAppConfigurationPush task, we no longer see the supplied prefix values being appended to the keys in our configuration. Version 3 works without issue in that our prefixes appear on the keys. We do see the ".appconfig.featureflag" appear on both versions but I am unsure if that is due to us providing that value in the prefix or if azure is managing that regardless. I have not tested versions between. Our prefix value does have a colon : in it, if that matters. 

Our working version 3 code: 
```
- task: AzureAppConfigurationPush@3
              displayName: "some display name"
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                AppConfigurationEndpoint: ${{ parameters.appConfigurationEndpoint }}
                ConfigurationFile: "${{ configurationFile }}"
                Separator: ';'
                Depth: ${{ parameters.depth }}
                Prefix: ".appconfig.featureflag/${{ somePrefixValueWith:ColonInIt }}"
                Label: ${{ parameters.label }}
                ContentType: "application/vnd.microsoft.appconfig.ff+json;charset=utf-8"
                Strict: ${{ parameters.strict }}
```

Our version 6 code:
```
- task: AzureAppConfigurationPush@6
              displayName: "some display name"
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                AppConfigurationEndpoint: ${{ parameters.appConfigurationEndpoint }}
                ConfigurationFile: "${{ configurationFile }}"
                Separator: ';'
                Depth: ${{ parameters.depth }}
                Prefix: ".appconfig.featureflag/${{ somePrefixValueWith:ColonInIt }}"
                Label: ${{ parameters.label }}
                ContentType: "application/vnd.microsoft.appconfig.ff+json;charset=utf-8"
                Strict: ${{ parameters.strict }}
                ImportMode: ${{ parameters.import_mode }}
                DryRun: ${{ parameters.dry_run }}
                Tags: ${{ parameters.tags }}
```

Our team requires the use of the prefix, so we will stay with version 3 for the immediate time being, but we would appreciate any insight that can be provided.

**Comment by MaryanneNjeri** [comment]
Hello @j-noel-b , to make sure I understand, with the Azure App Configuration Push@6, you are unable to add the prefix ".appconfig.featureflag/someprefix"  when pushing feature flags ?
This is cause Keys cannot start with the reserved prefix for feature flags. The update was introduced from version 5.

**Comment by j-noel-b** [comment]
> Hello @j-noel-b , to make sure I understand, with the Azure App Configuration Push@6, you are unable to add the prefix ".appconfig.featureflag/someprefix" when pushing feature flags ? If so this is cause keys cannot start with the reserved prefix(".appconfig.featureflag/") for feature flags. The update was introduced from version 5.

Sorry @MaryanneNjeri the copy-paste from v3 got away from me writing this ticket. 
Ultimately, we want to send a prefix value with a colon in it. Such as `Our:Prefix`
However, even sending a basic text block produces no prefix that I can see in our feature manager. 

Our feature json: 
{
  "FeatureManagement": {
      "Feature1": false,
      "Feature2": true
  }
}

Our task call: 
```
- task: AzureAppConfigurationPush@6
              displayName: "some display name"
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                AppConfigurationEndpoint: ${{ parameters.appConfigurationEndpoint }}
                ConfigurationFile: "${{ configurationFile }}"
                Separator: ';'
                Depth: ${{ parameters.depth }}
                Prefix: "OurPrefix"
                Label: ${{ parameters.label }}
                ContentType: "application/vnd.microsoft.appconfig.ff+json;charset=utf-8"
                Strict: ${{ parameters.strict }}
                ImportMode: ${{ parameters.import_mode }}
                DryRun: ${{ parameters.dry_run }}
                Tags: ${{ parameters.tags }}
```

The keys we end up with: 
```
.appconfig.featureflag/Feature1
.appconfig.featureflag/Feature2

```

**Comment by j-noel-b** [comment]
> Hello @j-noel-b , to make sure I understand, with the Azure App Configuration Push@6, you are unable to add the prefix ".appconfig.featureflag/someprefix" when pushing feature flags ? If so this is cause keys cannot start with the reserved prefix(".appconfig.featureflag/") for feature flags. The update was introduced from version 5.

Sorry @MaryanneNjeri - the copy-paste from v3 got away from me in writing this ticket. I sincerely apologize for the confusion in the description. 

Here is our feature json: 
{
  "FeatureManagement": {
      "Feature1": false,
      "Feature2": true
  }
}

here is our v6 task: 
```
- task: AzureAppConfigurationPush@6
              displayName: "some display name"
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                AppConfigurationEndpoint: ${{ parameters.appConfigurationEndpoint }}
                ConfigurationFile: "${{ configurationFile }}"
                Separator: ';'
                Depth: ${{ parameters.depth }}
                Prefix: "OurPrefix"
                Label: ${{ parameters.label }}
                ContentType: "application/vnd.microsoft.appconfig.ff+json;charset=utf-8"
                Strict: ${{ parameters.strict }}
                ImportMode: ${{ parameters.import_mode }}
                DryRun: ${{ parameters.dry_run }}
                Tags: ${{ parameters.tags }}
```

And here are the keys I am seeing in our feature manager:
```
.appconfig.featureflag/Feature1
.appconfig.featureflag/Feature2
```

Whereas I would expect to see: 
```
.appconfig.featureflag/OurPrefixFeature1
.appconfig.featureflag/OurPrefixFeature2
```

Ultimately, we would like a colon in our prefix value such as `Our:Prefix` but I can't seem to get the basic text of `OurPrefix` to append.
