### ISSUE TITLE
Required parameters?

### ISSUE THREAD

**Issue by rverberne** [Azure/AppConfiguration#811]
I get the error message:

`##[error]An unexpected error occurred. ClientSecretCredential: tenantId, clientId, and clientSecret are required parameters.`

Yaml:

```
  - task: AzureAppConfiguration@6
    displayName: Get Azure App Configuration
    inputs:
      azureSubscription: 'SC-Xyz'
      AppConfigurationEndpoint: 'https://xyz.azconfig.io'
      KeyFilter: '*'
```

- Why are these parameters required? Even though this is the YAML generated by the 'Add task wizard'.
