### ISSUE TITLE
Refresh by watching all selected keys

### ISSUE THREAD

**Issue by seba300** [Azure/AppConfiguration#843]
Hi, for now there is possibility to periodically resolve Key Vault references by doing sth like this:
```
configuration:
    refresh:
      enabled: true
      interval: 5m
      monitoring:
        keyValues:
          - key: "db_username"
            label: myTestEnv1
          - key: "db_password"
            label: myTestEnv1
```
I have to specify each key from key vault.

Is there any way to resolve them like this:
```
configuration:
    refresh:
      enabled: true
      interval: 5m
      monitoring:
        keyValues:
          - key: "db*"
            label: myTestEnv1
```
So appconfig will refresh each key which key name starts with "db"?

**Comment by RichardChen820** [comment]
The yaml you provided is configured for periodically watch the sentinel keys you selected for refreshing App Configuration Settings. To periodically resolve Key Vault references, you should:
```
secret:
    refresh:
       enabled: true
       interval: 5m
    target:
      secretName: secret-created-by-appconfig-provider
    auth:
      managedIdentityClientId: <your-user-assigned-managed-identity-client-id>
```

**Comment by RichardChen820** [comment]
To make the entire flow work, you could do this:
```
configuration:
    selectors:
      - keyFilter: app1*  # select all the key vault reference items you want
        labelFilter: myTestEnv1
secret:
    refresh:
       enabled: true
       interval: 5m
    target:
      secretName: secret-created-by-appconfig-provider
    auth:
      <any auth method you want to connect the key vault>
```
