### ISSUE TITLE
Support multiple provider instances per namespace

### ISSUE THREAD

**Issue by kleinmt** [Azure/AppConfiguration#862]
Using Azure App Configuration Kubernetes Provider v1.1.0, only one `AzureAppConfigurationProvider` resource can be created per namespace, due to conflicting child resource names, such as:

- Service Account: `az-appconfig-k8s-provider`
- Config Map: `az-appconfig-controller-manager-config`

### Use Case
When deploying multiple applications in one namespace, each of them may assume their own user assigned identity via Azure Workload Identity. Retrieving configuration values from the App Configuration store should use the application's identity. 
Since the providers service account name is not configurable, only one federated credential can be used to establish an OIDC-backed relationship, and as a result only one user assigned identity can be used per namespace. 
Leader election, which uses a shared config map for each provider instance, would probably suffer from a similar naming conflict.

Would it be possible to provision provider child resources with unique names, so that multiple instances of the provider can co-exist in one namespace?

> Tobias Kleinmann <<tobias.kleinmann@mercedes-benz.com>>, Mercedes-Benz Tech Innovation GmbH ([Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))

**Comment by linglingye001** [comment]
Hi @kleinmt ,  you can create multiple provider instances within each namespace. The property values in the `spec` section can be set differently based on the application. If each application requires access to the App Configuration store using its own user-assigned identity, you can refer to the documentation [use workload identity](https://learn.microsoft.com/en-us/azure/azure-app-configuration/reference-kubernetes-provider?tabs=default#use-workload-identity) for guidance on creating federated credentials for each identity. Subsequently, in each instance, you can replace the `managedIdentityClientId` with the user-assigned identity specific to the application.

```yaml
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  endpoint: <your-app-configuration-store-endpoint>
  target:
    configMapName: <target-configmap-name>
  auth:
    workloadIdentity:
      managedIdentityClientId: <your-managed-identity-client-id>
```

Should you have any further questions or need additional assistance, please feel free to reach out.

**Comment by kleinmt** [comment]
This would still require establishing a federated credential on each user-assigned identity with the single 'az-appconfig-k8s-provider' service account, which is technically possible but I'd rather have a 1:1 relationship between service accounts and user-assigned identities to ensure a fair separation of concerns.

This could be enabled by allowing the user to set the a serviceAccountName property, for example:
```yaml
[...]
spec:
  endpoint: <your-app-configuration-store-endpoint>
  target:
    configMapName: <target-configmap-name>
  auth:
    workloadIdentity:
      managedIdentityClientId: <your-managed-identity-client-id>
      serviceAccountName: <name-of-service-account>
```

Would this be something that you could consider for future releases of the provider?
