### ISSUE TITLE
Helm Chart Example - AzureAppConfigurationProvider Resource

### ISSUE THREAD

**Issue by thepaulmacca** [Azure/AppConfiguration#876]
I'm looking to try out the `AzureAppConfigurationProvider` resource as part of a helm chart - does anyone have a working example that they could share please?

It would be a good example to have in the docs as well I think

Here's my scenario - I have an app in the `src/MyWebApp` folder, with a helm chart in `src/MyWebApp/charts/my-web-app`. Base settings are in the `appsettings.json` file, and for Dev config, a `DevConfig.json` file exists, and this is pushed to the Dev store via the pipeline task

I have helm overrides in each environment, so the resource will need to use the config relevant to each file/store

I hope that makes sense - I'm still trying to get my head around how this should be working 

Thanks

**Comment by linglingye001** [comment]
Hi @thepaulmacca ,  you can 

1. create a `config` folder and a json file like `src/MyWebApp/config/appConfig.json`.
2. add the JSON file to the configuration source by calling the `AddJsonFile` method. Such as `builder.Configuration.AddJsonFile("config/appConfig.json"); `

When deploy the app in AKS, the ConfigMap generated by kubernetes provider can be mounted at the `config` path in a data volume and is consumable as a JSON file. More information can be found [setup-the-app-configuration-kubernetes-provider](https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-kubernetes-service#setup-the-app-configuration-kubernetes-provider).

In this way you can use helm override values for different environment, and the app will consume relevant mounted config file. 
Let me know if you have any further questions or encounter any issues. Thanks.

**Comment by thepaulmacca** [comment]
Hi, thanks for coming back to me - something's not computing with me here. What if I have multiple files, like `appConfig.Development.json`, `appConfig.Staging.json`, `appConfig.Production.json` for example?

**Comment by RichardChen820** [comment]
Your deployment would mostly looks like this 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-demo
  namespace: mymapp-{{.value.label}}
  labels:
    app: aspnetapp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  aspnetapp-demo
  template:
    metadata:
      labels:
        app:  aspnetapp-demo
    spec:
      containers:
      - name: aspnetapp
        image: myregistry.azurecr.io/aspnetapp:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume 
        configMap: 
          name: configmap-created-by-appconfig-provider

```

**Comment by thepaulmacca** [comment]
Thanks for coming back to me @linglingye001 @RichardChen820 I'll give these suggestions a try - it'll click for me eventually 😅

**Comment by RichardChen820** [comment]
Short answer is yes, you just ignore it. 

The reason is that `appsettings.json` and `appsettings.Development.json` in the root directory could be recognized by asp.net by default. In most cases, people just leverage it, put settings in that two files. But in container (Kubernetes) case, we need to mount configuration file(s). Volume mount only supports mount entire path, means if the config file is in the root path, mount will lead to losing other files (pages, DLLs ), hence we have to create a dedicated directory for configuration and mount configuration files to that directory in container.

**Comment by thepaulmacca** [comment]
Got it, thanks @RichardChen820 I'm just trying this out

**Comment by thepaulmacca** [comment]
Sorry for not getting back to you sooner @RichardChen820 but I just cannot get this to work with a file in the `config` folder. I'm getting the below error

```go
E0229 16:32:04.795531       1 appconfigurationprovider_controller.go:245] Fail to create the target ConfigMap or Secret of AzureAppConfigurationProvider 'appconfigurationprovider-example' in 'testing' namespace: ConfigMap "configmap-created-by-appconfig-provider" is invalid: data[config/appConfig.json]: Invalid value: "config/appConfig.json": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

Any ideas? Here's my current config if it helps

`app-config.yaml` template `target`

```
  target:
    configMapName: configmap-created-by-appconfig-provider
    configMapData:
         type: json
         key: appConfig.json
```

Helm values

```
volumeMounts:
  - name: config-volume
    mountPath: /app/config

volumes:
  - name: config-volume
    configMap:
      name: configmap-created-by-appconfig-provider
```

Any help would be appreciated - thanks

**Comment by RichardChen820** [comment]
Are you sure this yaml is the one you are using when you see this error?
```
target:
    configMapName: configmap-created-by-appconfig-provider
    configMapData:
         type: json
         key: appConfig.json
```
From you error log, seems you were trying such yaml
```
 target:
    configMapName: configmap-created-by-appconfig-provider
    configMapData:
         type: json
         key: config/appConfig.json
```

**Comment by thepaulmacca** [comment]
Sorry for not coming back to you sooner @RichardChen820 - I seem to be halfway there with this config (my `appConfig.json` file is now in the root like the docs)

```yaml
volumeMounts:
  - name: config-volume
    mountPath: /app/appConfig.json
    subPath: appConfig.json

volumes:
  - name: config-volume
    configMap:
      name: configmap-created-by-appconfig-provider
      items:
        - key: appConfig.json
          path: appConfig.json
```

My ConfigMap now mounts and I can see the correct values in it - but my screen is blank. I don't see any errors in either pod or provider logs though
