### ISSUE TITLE
E0627: Fail to create the target ConfigMap or Secret of AzureAppConfigurationProvider no token file specified. Check pod configuration or set TokenFilePath in the options

### ISSUE THREAD

**Issue by bearnais-obtus** [Azure/AppConfiguration#935]
Hello folks,

# Installation
helm install azureappconfiguration.kubernetesprovider \
    oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider \
    --namespace azappconfig-system \
    --create-namespace

Created a Managed Identity and made a federation to use Workload Id using this doc : https://learn.microsoft.com/en-us/azure/azure-app-configuration/reference-kubernetes-provider?tabs=default#use-workload-identity

Assigned the role [App Configuration Data Reader](https://portal.azure.com/#) on the desired App Config

# The issue

```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: myconfig
  namespace: customnamespace (not the same as the one where the helm chart is installed)
spec:
  endpoint: "https://myconfig.azconfig.io"
  target:
    configMapName: myconfig
  auth:
    workloadIdentity:
      managedIdentityClientId: msi-client-id
```

Gives me error, from the console output of pod az-appconfig-k8s-provider 
`E0627: Fail to create the target ConfigMap or Secret of AzureAppConfigurationProvider no token file specified. Check pod configuration or set TokenFilePath in the options`

And does not create the config map.
As a workaround I am using the agent pool managed identity, and it works fine, but i'd prefer use workload to be consistent as I use workload identity to access key vaults and create secrets from them.

As a note, I can see that the service account is as following, and does not mention the client id of the managed identity in its annotations :
apiVersion: v1                                                                                                                                                                    
│ kind: ServiceAccount                                                                                                                                                               
│ metadata:                                                                                                                                                                         
│   annotations:                                                                                                                                                                     
│     azure.workload.identity/client-id: ""                

Can you tell me what I'm missing here ?
Thanks !
